# Generated by Django 3.2.12 on 2024-04-22 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Títol del item')),
                ('material_type', models.TextField(max_length=100, verbose_name='Material del que es composa')),
                ('signature', models.CharField(max_length=100, verbose_name='Signatura')),
            ],
            options={
                'verbose_name': 'Item del catàlog',
                'verbose_name_plural': 'Items dels catàlogs',
            },
        ),
        migrations.CreateModel(
            name='ItemCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Available', max_length=20, verbose_name='Disponibilitat')),
                ('id_copy', models.CharField(max_length=100, verbose_name='Id del exemplar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioApp.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Exemplar del item',
                'verbose_name_plural': 'Exemplars dels items',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rols',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioApp.item')),
                ('author', models.CharField(max_length=100, verbose_name='Autor del item')),
                ('edition_date', models.DateField(verbose_name="Data de l'edició")),
                ('CDU', models.TextField(max_length=100)),
                ('ISBN', models.TextField(max_length=13)),
                ('publisher', models.CharField(max_length=100, verbose_name='Editorial')),
                ('colection', models.CharField(max_length=100, verbose_name='Col·lecció')),
                ('pages', models.PositiveIntegerField(verbose_name='Pàgines')),
            ],
            options={
                'verbose_name': 'Llibre',
                'verbose_name_plural': 'Llibres',
            },
            bases=('biblioApp.item',),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioApp.item')),
                ('author', models.CharField(max_length=100, verbose_name='Autor del item')),
                ('edition_date', models.DateField(verbose_name="Data de l'edició")),
                ('discography', models.CharField(max_length=100, verbose_name='Discografía')),
                ('style', models.CharField(max_length=100, verbose_name='Estil')),
                ('duration', models.TimeField(verbose_name='Duració')),
            ],
            options={
                'verbose_name': 'CD',
                'verbose_name_plural': "CD's",
            },
            bases=('biblioApp.item',),
        ),
        migrations.CreateModel(
            name='Dispositive',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioApp.item')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca del dispositiu')),
                ('dispo_type', models.CharField(max_length=100, verbose_name='Tipus de dispositiu')),
            ],
            options={
                'verbose_name': 'Dispositiu',
                'verbose_name_plural': 'Dispositius',
            },
            bases=('biblioApp.item',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('surname', models.CharField(max_length=100, verbose_name='Cognom')),
                ('surname2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segon cognom (opcional)')),
                ('date_of_birth', models.DateField(verbose_name='Data de naixement')),
                ('center', models.CharField(max_length=100, verbose_name='Centre al que pertany')),
                ('cycle', models.CharField(max_length=100, verbose_name='Curs al que pertany')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Imatge de perfil')),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correu electrònic')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioApp.role', verbose_name="Rol d'usuari")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(auto_now_add=True, verbose_name='Data de la reserva')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioApp.itemcopy', verbose_name='Exemplar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioApp.userprofile', verbose_name='Usuari')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reserves',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Data de la petició')),
                ('request_text', models.TextField(verbose_name='Descripció de la petició')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioApp.userprofile', verbose_name='Usuari')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('route', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioApp.userprofile')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(auto_now_add=True, verbose_name='Data de la solicitud del prèstec')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Data del final del prèstec')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioApp.itemcopy', verbose_name='Exemplar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioApp.userprofile', verbose_name='Usuari')),
            ],
            options={
                'verbose_name': 'Prèstec',
                'verbose_name_plural': 'Prèstecs',
            },
        ),
    ]
