# Generated by Django 5.0.4 on 2024-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0002_alter_request_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='null@null.com', max_length=254, unique=True, verbose_name='Correu electrònic'),
            preserve_default=False,
        ),
    ]
