# Generated by Django 5.0.4 on 2024-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0004_alter_log_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telèfon'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(verbose_name='Data del final del prèstec'),
        ),
    ]
