# Generated by Django 5.0.4 on 2024-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0005_userprofile_phone_alter_loan_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='loan_available',
            field=models.BooleanField(default=True, verbose_name='Item disponible per prestar a alumnes'),
        ),
    ]
