# Generated by Django 5.0.4 on 2024-04-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0005_userprofile_phone_alter_loan_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
