# Generated by Django 5.0.4 on 2024-04-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0006_userprofile_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
