# Generated by Django 5.0.4 on 2024-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0006_item_loan_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom del centre')),
            ],
            options={
                'verbose_name': 'Centre',
                'verbose_name_plural': 'Centres',
            },
        ),
    ]
