# Generated by Django 5.0.4 on 2024-04-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0006_item_loan_available'),
        ('biblioApp', '0007_alter_log_user'),
    ]

    operations = [
    ]
