# Generated by Django 5.0.4 on 2024-04-29 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0007_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioApp.center', verbose_name='Centre'),
        ),
    ]
