# Generated by Django 5.0.4 on 2024-04-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0008_alter_userprofile_center'),
        ('biblioApp', '0008_merge_0006_item_loan_available_0007_alter_log_user'),
    ]

    operations = [
    ]
