# Generated by Django 5.0.4 on 2024-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0008_alter_userprofile_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data de naixement'),
        ),
    ]
