# Generated by Django 5.0.4 on 2024-04-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0009_merge_20240429_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='DNI'),
        ),
    ]
